merge work sprint from devel into main
katzenpost/katzenpost pull request #148
Opened 2022-12-25 19:10 UTC by mixmasala

The devel branch fixes issues with the consensus protocol, removes duplicated abstractions in core/pki, improves container based workflow to use podman so that it can be used rootlessly, fixes issues with client and mix authenticatio, and removes the options for case insensitive session IDs.

2022-12-25 21:03 UTC, david415 requested changes
please also update katzenpost/docs/specs/pki.rst... if you don't want to do this in this same pull request then please open a ticket to update the specification documents in order to resolve this PR request for changes.

2022-12-25 21:04 UTC, david415 commented
looks good to me... but we do need to keep the specification documents up to date... so update the pki design doc and include the details about your wire protocol commands and the phases of the dirauth voting protocol.

2022-12-25 21:12 UTC, mixmasala commented on core/sphinx/path/path.go
> +			return nil, fmt.Errorf("path: invalid destination (non provider): %x", dst.IdentityKey.Sum256())
Endpoint?

2022-12-25 21:17 UTC, mixmasala commented on authority/cmd/voting/authority.toml.sample
> +[Server]
Because the Authority type is defined elsewhere for the Voting PKI peers

2022-12-25 21:17 UTC, mixmasala commented
https://github.com/katzenpost/katzenpost/issues/149

2022-12-25 21:18 UTC, mixmasala commented on authority/cmd/voting/authority.toml.sample
> +[Server]
Because the Authority type is defined elsewhere for the Voting PKI peers.

2022-12-25 23:58 UTC, david415 approved these changes

2022-12-26 14:08 UTC, yippyskippy commented on core/sphinx/path/path.go
> +			return nil, fmt.Errorf("path: invalid destination (non provider): %x", dst.IdentityKey.Sum256())
IIUC include `mix` so `endpoint mix` maybe?

2022-12-26 17:37 UTC, mixmasala commented
Added fixes for #150 #151 which were caught because we now generate the testing mixnet configuration at build time from parameters that were more aggressive (shorter per-hop delays)

2022-12-27 03:15 UTC, leif commented on core/sphinx/path/path.go
> +			return nil, fmt.Errorf("path: invalid destination (non provider): %x", dst.IdentityKey.Sum256())
we should change the term provider, but it's in many places (including right here already) and we should think more about the right word.

2022-12-27 13:07 UTC, merged