docker/Makefile: add clean-bin target
katzenpost/katzenpost pull request #327
Opened 2023-06-17 12:15 UTC by leif

this is useful for creating a testnet with an old version and then upgrading it without deleting the network state (as `clean-local` does).

2023-06-17 19:21 UTC, threebithacker requested changes

2023-06-17 19:21 UTC, threebithacker commented on docker/Makefile
> +	rm -vf $(net_name)/*.$(distro)
```suggestion
	rm -vf ./$(net_name)/*.$(distro)
```
how about this, then at works we nuke `.//.`? :-)

2023-06-17 19:21 UTC, threebithacker commented on docker/Makefile
> +	rm -vf $(net_name)/*.$(distro)
(which should be fine since it's not `rm -r`)

2023-06-23 11:09 UTC, mixmasala approved these changes
thanks

2023-06-24 13:03 UTC, merged