Add cborplugin async send
katzenpost/katzenpost pull request #373
Opened 2023-08-26 12:05 UTC by mixmasala

Refactor cborplugin so that plugins can send responses asynchronously from requests

2023-08-26 12:08 UTC, mixmasala commented
Question: how should the first-hop delay be chosen for SURB-ACK replies where the service plugin may use the SURB to reply any time within a valid Epoch?

2023-08-31 12:07 UTC, mixmasala reviewed
I've added comments where I think improvements should be made.

2023-08-31 13:44 UTC, mixmasala commented
note, this PR merges https://github.com/katzenpost/katzenpost/pull/346

2023-09-01 18:19 UTC, david415 requested changes
apply delay BEFORE service processing payload

2023-09-01 18:19 UTC, david415 commented on server/internal/provider/kaetzchen/cbor_plugins.go
> +					// Set the packet queue delay
doesn't seem fix the delay problem, you are applying the delay after the service processes the packet. we need the delay to happen before the service processes the payload.

2023-09-01 18:21 UTC, david415 commented
> Question: how should the first-hop delay be chosen for SURB-ACK replies where the service plugin may use the SURB to reply any time within a valid Epoch?

I think the first hop on the SURB replay (let's not call it an ACK) should be zero delay. The delay should be applied before the service processes the payload; because if the service processes the payload by making some kind of Internet traffic then the packet will be correlated with that network activity.

2023-09-01 18:25 UTC, david415 commented on server/internal/packet/packet.go
> +	// pick a random delay to use for firstHop
We don't want to merge any PR that reduces the client's understanding of the RTT in my humble opinion; but we can probably fix this by applying a large fraction of the delay before the service processes the payload and optionally any remaining relay afterwards. We don't want service related network events to be linkable to the packets routed to the service Provider.

2023-09-05 16:05 UTC, david415 commented on memspool/server/cmd/memspool/main.go
> +		go func() {
are we even using memspool anymore?

2023-09-05 16:06 UTC, david415 commented on server/cborplugin/client.go
>  // Marshal serializes Response
yeah that sounds good if we have a use case for that. if not then i suggest saving that work until we actually need it.

2023-10-02 21:04 UTC, mixmasala commented on memspool/server/cmd/memspool/main.go
> +		go func() {
yes

2024-01-27 17:55 UTC, mixmasala commented
Oops, re-reading this I see that we discussed adding the delay before processing the kaetzchen request.
https://github.com/katzenpost/katzenpost/issues/509

2024-01-27 17:59 UTC, mixmasala commented
I think preserving the existing behavior is OK for now but we should address #509 somehow, in combination with #508

2024-06-01 03:54 UTC, david415 approved these changes

2024-06-01 04:02 UTC, david415 commented
@mixmasala we can merge this as soon as all the CI tests pass. the code quality is pretty good. i like how the reunion server was modified more than i like how the panda server was modified... because in the reunion case you at least keep track of the goroutine. but the code changes to the mix server itself are very good in my opinion.

2024-06-01 04:53 UTC, david415 approved these changes

2024-06-01 04:54 UTC, david415 approved these changes

2024-06-01 04:55 UTC, merged